version: '3.8'

services:

  database:
    image: mongo
    volumes:
        - ./database:/data/db
    networks:
      - network_db
      - network_gui
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  db_management:
    image: mongo-express
    restart: always
    networks:
      - network_gui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/

  backend:
    build: ./service
    networks:
      - network_db
    ports:
      - 6000:6000
    environment:
      - MONGODB_CONNSTRING_ENV=mongodb://root:example@database:27017/
      - MONGODB_DBNAME_ENV=tema_sprc_02

volumes:
  dbdata:
  app_src:

networks:
  network_db:
  network_gui:
